name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/**'


env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_ZONE: ${{ secrets.GCP_ZONE }}
  IMAGE: data-corner
  TAG: staging

jobs:
  Deploy:
    name: Setup
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    # Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    # Configure Docker to use the gcloud command-line tool as a credential
    - run: gcloud --quiet auth configure-docker

    - name: Build
      run: |-
        docker build \
          --tag "eu.gcr.io/$PROJECT_ID/$IMAGE:$TAG" \
          .
    # Push the Docker image to Google Container Registry
    - name: Publish
      run: docker -- push eu.gcr.io/$PROJECT_ID/$IMAGE:$TAG
  
    - name : Deploy Cloud Run
      run : |-
        gcloud run deploy $IMAGE \
        --image eu.gcr.io/$PROJECT_ID/$IMAGE:$TAG \
        --platform managed \
        --region $GCP_ZONE \
        --memory 1024Mi \
        --labels=type=$TAG #\
#        --no-allow-unauthenticated \
#        --ingress internal \
